author: Chromium Authors <mojo-dev@googlegroups.com>
dependencies:
  mojo: 0.4.28
  mojo_services: 0.4.35
description: A meta package for the Dart Mojo SDK
homepage: https://github.com/domokit/mojo
name: mojo_sdk
version: 0.2.32
